apiVersion: app.kiegroup.org/v1alpha1
kind: KogitoBuild
metadata:
  name: pmml-tracing-quarkus
spec:
  type: RemoteSource
  gitSource:
    contextDir: pmml-tracing-quarkus
    uri: "https://https://github.com/gitgabrio/pmml-tracing-quarkus/"
  # set your maven nexus repository to speed up the build time
  #mavenMirrorURL:
---
apiVersion: app.kiegroup.org/v1alpha1
kind: KogitoRuntime
metadata:
  name: pmml-tracing-quarkus
spec:
  kafka:
    useKogitoInfra: true
